version: '3.8'

services:
  # backend:
  #   build: ./backend
  #   container_name: nestjs-backend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./backend:/app
  #   environment:
  #     - MONGO_URI=mongodb://mongodb:27017/dyslexia
  #   depends_on:
  #     - mongodb
  #   restart: always

  # frontend:
  #   build: ./frontend
  #   container_name: react-frontend
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./frontend:/app
  #   depends_on:
  #     - backend
  #   restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    restart: always

volumes:
  mongodb_data:
    driver: local
